script:
   - echo $DOCKER_PASSWD | docker login --username $DOCKER_USERNAME --password-stdin
   - docker build --target test --tag todo_test .
   - docker run todo_test tests
   - docker run todo_test tests_int
   - docker run -e TRELLO_API_KEY -e TRELLO_API_TOKEN todo_test tests_e2e

   - docker build --target production --tag todo-app:latest . 
   - docker push todo-app:latest

notifications:
  email:
    recipients:
      - jeremybrex@gmail.com
    on_success: always
    on_failure: always

env:
 global:
   - DOCKER_USERNAME = "j3rry99"