version: "3.8"

services:
  app:
    env_file: .env
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    image: todo-app/prod
    ports:
      - "5000:5000"

# docker build --target production --tag todo_app .
# docker run --env-file .env -p 5000:5000 todo_app
# docker-compose up -f docker-compose_prod | stop